// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1NMnQ9qJrsGucT7OdyjIs6jT7c9N7q4',
    appId: '1:128995635604:web:27eefff966105b8b9f1f81',
    messagingSenderId: '128995635604',
    projectId: 'home-visit-d26b1',
    authDomain: 'home-visit-d26b1.firebaseapp.com',
    storageBucket: 'home-visit-d26b1.appspot.com',
    measurementId: 'G-SSTD72QBPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeuuVGgZ3guHiXlcPO_udRAe8_m-9W3IE',
    appId: '1:128995635604:android:a473823650ece4709f1f81',
    messagingSenderId: '128995635604',
    projectId: 'home-visit-d26b1',
    storageBucket: 'home-visit-d26b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArpXEJaGXRS3dSkQH7rO_q2HJo-VZKuz0',
    appId: '1:128995635604:ios:dbd61b5dda25d9ff9f1f81',
    messagingSenderId: '128995635604',
    projectId: 'home-visit-d26b1',
    storageBucket: 'home-visit-d26b1.appspot.com',
    iosBundleId: 'com.iso.homeVisit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArpXEJaGXRS3dSkQH7rO_q2HJo-VZKuz0',
    appId: '1:128995635604:ios:dbd61b5dda25d9ff9f1f81',
    messagingSenderId: '128995635604',
    projectId: 'home-visit-d26b1',
    storageBucket: 'home-visit-d26b1.appspot.com',
    iosBundleId: 'com.iso.homeVisit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk1NMnQ9qJrsGucT7OdyjIs6jT7c9N7q4',
    appId: '1:128995635604:web:de9770326bb8b1e29f1f81',
    messagingSenderId: '128995635604',
    projectId: 'home-visit-d26b1',
    authDomain: 'home-visit-d26b1.firebaseapp.com',
    storageBucket: 'home-visit-d26b1.appspot.com',
    measurementId: 'G-NCYMCM4P67',
  );
}
